# Hypercorn config settings.
# Ref: https://hypercorn.readthedocs.io/en/latest/how_to_guides/configuring.html

bind = ":8080"
workers = 4
# Give workers an expiry
max_requests = 2048
max_requests_jitter = 256
# Request logging
accesslog = "-"      # stdout
errorlog = "-"       # stderr
loglevel = "WARNING"
