apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcheck-deployment
spec:
  template:
    spec:
      containers:
        - name: healthcheck
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: healthcheck-env-prod
                optional: false
