apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: healthcheckserver-statefulset
spec:
  template:
    spec:
      volumes:
        - name: healthcheck-data
          persistentVolumeClaim:
            claimName: healthcheck-data-prod
      initContainers:
        - name: data-vol-chown
          image: busybox
          command:
            - /bin/chown
            - -R
            - '1000:1000'
            - /app/data_dir
          volumeMounts:
            - mountPath: /app/data_dir
              name: healthcheck-data
      containers:
        - name: healthcheckserver
          envFrom:
            - secretRef:
                name: healthcheck-env-prod
                optional: false
          volumeMounts:
            - mountPath: /app/data_dir
              name: healthcheck-data
