apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: healthcheckserver-statefulset
spec:
  template:
    spec:
      volumes:
        - name: healthcheck-data
          persistentVolumeClaim:
            claimName: healthcheck-data-prod
      containers:
        - name: healthcheckserver
          envFrom:
            - secretRef:
                name: healthcheck-env-prod
                optional: false
          volumeMounts:
            - mountPath: /app/data_dir
              name: healthcheck-data
